spring:
    r2dbc:
        url: r2dbc:postgresql://localhost:5432/postgres?schema=person
        username: root
        password: root

logging:
    level:
        io.r2dbc.postgresql.QUERY: DEBUG # for queries
        io.r2dbc.postgresql.PARAM: DEBUG # for parameters

reactive.feign:
    hystrix.enabled: false
    logger.enabled: true
    client.config.default.options:
        connectTimeoutMillis: 3000
        readTimeoutMillis: 5000
